### ISSUE TITLE
Panic on "Non-ACGTN nucleotide encountered!" misses the illegal character

### ISSUE THREAD

**Issue by sebschmi** [luizirber/nthash#10]
When nthash panics with "Non-ACGTN nucleotide encountered!", it does not print the illegal character.

Instead, it should print something like "Non-ACGTN nucleotide encountered: X".

**Comment by luizirber** [comment]
Thanks for the report, @sebschmi! Fixed in #12, released as [0.5.1](https://crates.io/crates/nthash/0.5.1)

**Comment by sebschmi** [comment]
Thank you very much!
________________________________
